### ISSUE TITLE
Unable to config heroku

### ISSUE THREAD

**Issue by moosergamer** [eyupbarlas/Crypto-Trading-Bot-with-Tradingview-Binance-Heroku-and-Telegram#1]
Bro please give the instructions to heroku installation process

**Comment by eyupbarlas** [comment]
### Heroku Installation and Deployment
- [ ]  The **Heroku CLI** requires **Git**. You have to make sure that Git is installed and setup is done.
* [Download Link](https://git-scm.com/downloads)
* [Setting up Git](https://docs.github.com/en/get-started/quickstart/set-up-git)
- [ ]  Then you have to download the installer for [Heroku CLI](https://devcenter.heroku.com/articles/getting-started-with-python#set-up). After the installment, you can use `heroku` command from your command shell. You should enter `heroku login` to your command line to authenticate your connection.
- [ ] After that, go to the [Heroku Dashboard](https://dashboard.heroku.com/apps) in your browser and select "Create new app" from top right. After selecting a name and choosing a region, a page with deployment instructions will come up.
- [ ] Now, you can create your project folder and follow the instructions given on the page.

![2021-09-15 14_23_27-bzzmans-test-app · Heroku-git _ Heroku](https://user-images.githubusercontent.com/72407947/133424967-5ecb30df-5612-4e98-9dc0-3a2b2bda6514.jpg)

- [ ] You can check for logs after deploying the project using `heroku logs --tail` command on your command shell.

**Comment by eyupbarlas** [comment]
Was it helpful, @moosergamer?
